CREATE TABLE professional_day_breack_time
(
ID VARCHAR(255) NOT NULL,
INIT_TIME TIME NOT NULL,
END_TIME TIME NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL,
PROFESSIONAL_DAY_ID VARCHAR(255),
CREATE_DATE DATE,
UPDATE_DATE DATE,
CONSTRAINT pk_professional_day_breack_time PRIMARY KEY (id),
CONSTRAINT pk_professional_day_breack_time_professional_day FOREIGN KEY (PROFESSIONAL_DAY_ID) REFERENCES professional_day(id) ON DELETE CASCADE
);
