CREATE TABLE professional_day_hour
(
ID  VARCHAR(255) NOT NULL,
PROFESSIONAL_DAY_HOUR_DATE DATE,
DATE_TIME TIME NOT NULL,
AVAILABLE BOOLEAN DEFAULT FALSE,
PROFESSIONAL_ID VARCHAR(255) NOT NULL,
CREATE_DATE DATE,
UPDATE_DATE DATE,
CONSTRAINT pk_professional_day_hour PRIMARY KEY (id)
);
